[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# CRITICAL: SPA routing - this MUST be first and catch all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# API proxy to your EC2 backend (update with your actual EC2 IP)
[[redirects]]
  from = "/api/*"
  to = "http://your-ec2-ip:3000/api/:splat"
  status = 200
  force = true

# WebSocket proxy to your EC2 backend (update with your actual EC2 IP)
[[redirects]]
  from = "/ws"
  to = "http://your-ec2-ip:3000/ws"
  status = 200
  force = true 